//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookStoreEntities : DbContext
    {
        public BookStoreEntities()
            : base("name=BookStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Counteragents> Counteragents { get; set; }
        public virtual DbSet<DiscountCards> DiscountCards { get; set; }
        public virtual DbSet<Formats> Formats { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Nomenclature> Nomenclature { get; set; }
        public virtual DbSet<OrderParts> OrderParts { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Requisites> Requisites { get; set; }
        public virtual DbSet<SellParts> SellParts { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<ShipmentParts> ShipmentParts { get; set; }
        public virtual DbSet<Shipments> Shipments { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
    }
}
