//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderParts = new HashSet<OrderParts>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int RegionID { get; set; }
        public int CityID { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartment { get; set; }
        public string Phone { get; set; }
        public decimal Total { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> DiscountID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual DiscountCards DiscountCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderParts> OrderParts { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
