//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisites
    {
        public int ID { get; set; }
        public decimal CorAccount { get; set; }
        public decimal BIC { get; set; }
        public int Counteragents_ID { get; set; }
        public int BankID { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual Counteragents Counteragents { get; set; }
    }
}
