//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sells()
        {
            this.SellParts = new HashSet<SellParts>();
        }
    
        public int ID { get; set; }
        public System.DateTime SellDate { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual DiscountCards DiscountCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellParts> SellParts { get; set; }
    }
}
