//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentParts
    {
        public int ID { get; set; }
        public int ShipmentID { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public int NomenclatureID { get; set; }
    
        public virtual Nomenclature Nomenclature { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
