//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipments()
        {
            this.ShipmentParts = new HashSet<ShipmentParts>();
        }
    
        public int ID { get; set; }
        public decimal Total { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int CounteragentID { get; set; }
        public int ContractID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Counteragents Counteragents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentParts> ShipmentParts { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
